name: Develop
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  CI:
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install base dependencies
        run: npm install
      - name: Bootstrap
        run: lerna bootstrap
      - name: Run ESLint
        run: lerna run lint
      - name: Run Tests
        run: lerna run test

