name: Zeal Github Actions
on: [push]
jobs:
  setup-environment:
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
  perform-linting:
    runs-on: windows-latest
    needs: [setup-environment]
    steps:
      - name: Install base dependencies
        run: npm install
      - name: Bootstrap
        run: lerna bootstrap
      - name: Run ESLint
        run: lerna run lint